### ISSUE TITLE
can't past test

### ISSUE THREAD

**Issue by JizongL** [freeCodeCamp/boilerplate-npm#55]
I did as instructed, I forked the repository, and added the "author":"name", to the package.json and it passed the test, but it keeps saying the author key is not valid. I also did the same with the Glitch file, but it didn't work either. would you please let me know how to do that, is there a bug?

**Comment by Forz70043** [comment]
try to clone project

**Comment by raisedadead** [comment]
Hi

Thanks for reporting this issue. 

- Check [these troubleshooting steps](https://www.freecodecamp.org/forum/t/how-to-report-a-bug/19543) first.
