### ISSUE TITLE
Node.js Version is outdated, it should be updated to 8.11.x

### ISSUE THREAD

**Issue by ztickm** [freeCodeCamp/boilerplate-npm#9]
### Description of the problem and how to reproduce it:

The Node.js version used on [ `package.json`](./../blob/gomix/package.json) is **4.4.5**, a version no longer maintained (read possible security flaws) according to the [Node.js release timeline](https://github.com/nodejs/Release#release-schedule).  

On Glitch.com if the version is anything un-maintained it will automatically be replaced by **8.11.2**, as you can see in the following screenshot:
![screenshot](https://user-images.githubusercontent.com/7467165/41454577-36fdbc80-707a-11e8-9cfd-7fd85418e2d8.png)

### Suggestion
I would replace the version by **8.11.2**, the last 8.x version supported by glitch.com to date; or by **8.11.3**, the last [8.x version](https://nodejs.org/dist/latest-v8.x/) to date.  
It is to note that using **8.11.3** on glitch.com will fall back to **8.11.2**, but it's most probably momentary and **8.11.3** will eventually be used.  

**_P.S._** It's not clear if this is the main repo or not. Will send a PR anyway.

**Comment by anku255** [comment]
@ztickm Hi! Instead of writing `8.11.3`, wouldn't it be better to write `^8.11.3` which indicates anything until `9.x.x` is fine?

**Comment by ztickm** [comment]
The engines part has a different syntax, it doesn't take `^`, check [this](https://docs.npmjs.com/files/package.json#engines) for more about that.  
The thing is, even the accepted syntaxes won't work on Glitch, so I think it's a good idea to keep it "static"

**Comment by anku255** [comment]
Yeah, it seems Glitch automatically installs the node versions which are available. If you write a node version `8.9.x`, it will always install `8.9.4`.

**Comment by Bouncey** [comment]
Closed via #10
